<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Lucene.Net" Version="4.8.0-beta00017" />
		<PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta00017" />
		<PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00017" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
		<PackageReference Include="PDFiumSharp" Version="1.4660.0-alpha1" />
		<PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
		<PackageReference Include="Tesseract" Version="5.2.0" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="tessdata\eng.traineddata">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Settings.Designer.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Settings.settings</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>

</Project>
